"""
Pydantic schemas for API request/response validation.
These are transport-layer models, separate from ORM models.
"""
from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, HttpUrl, field_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Channel(str, Enum):
    social_media = "social_media"
    email = "email"
    paid_ads = "paid_ads"
    seo = "seo"
    word_of_mouth = "word_of_mouth"
    app_store = "app_store"
    other = "other"


class Archetype(str, Enum):
    early_adopter = "early_adopter"
    pragmatist = "pragmatist"
    conservative = "conservative"
    skeptic = "skeptic"
    influencer = "influencer"
    price_sensitive = "price_sensitive"
    power_user = "power_user"
    casual_user = "casual_user"


class DecisionAuthority(str, Enum):
    individual = "individual"
    recommender = "recommender"
    decision_maker = "decision_maker"


class InteractionType(str, Enum):
    ignored = "ignored"
    viewed = "viewed"
    clicked = "clicked"
    read = "read"
    purchased = "purchased"
    abandoned = "abandoned"
    shared = "shared"
    reviewed = "reviewed"


class SimulationStatus(str, Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


# ---------------------------------------------------------------------------
# Product Input
# ---------------------------------------------------------------------------


class ProductInput(BaseModel):
    """What the user submits to kick off a simulation."""

    name: str = Field(..., min_length=2, max_length=120, description="Product name")
    description: str = Field(
        ...,
        min_length=50,
        max_length=8000,
        description="Landing page copy or full product description",
    )
    price_usd: float = Field(..., gt=0, description="Price in USD")
    channel: Channel = Field(
        default=Channel.social_media, description="Primary acquisition channel"
    )
    target_market: str = Field(
        default="",
        max_length=500,
        description="Optional: describe the intended audience",
    )
    landing_url: str | None = Field(
        default=None, description="Optional: URL of the real landing page"
    )
    num_agents: int = Field(
        default=50, ge=10, le=2000, description="Number of synthetic personas to generate (swarm mode: 500+)"
    )

    @field_validator("price_usd")
    @classmethod
    def round_price(cls, v: float) -> float:
        return round(v, 2)


# ---------------------------------------------------------------------------
# Simulated Agent (Persona)
# ---------------------------------------------------------------------------


class PainPoint(BaseModel):
    topic: str
    intensity: int = Field(..., ge=1, le=10, description="1 = mild annoyance, 10 = critical pain")


class SimulatedAgentProfile(BaseModel):
    """Rich persona generated by the Ethnographer agent."""

    agent_id: str = Field(..., description="Unique ID for this persona, e.g. 'agent_042'")
    name: str
    age: int = Field(..., ge=18, le=80)
    gender: str
    location: str
    occupation: str
    annual_income_usd: float = Field(..., ge=0)
    archetype: Archetype
    tech_savviness: int = Field(..., ge=1, le=10)
    pain_points: list[PainPoint]
    goals: list[str] = Field(default_factory=list, max_length=5)
    preferred_channels: list[Channel] = Field(default_factory=list)
    cognitive_biases: list[str] = Field(default_factory=list, description="e.g. ['loss aversion', 'social proof']")
    willingness_to_pay_usd: float = Field(..., ge=0)
    
    # Advanced Precision Fields
    current_tools: list[str] = Field(default_factory=list, description="Competitors or tools currently used")
    switching_cost_tolerance: int = Field(default=5, ge=1, le=10, description="1 = hates changing tools, 10 = loves migrating")
    decision_authority: DecisionAuthority = Field(default=DecisionAuthority.individual)
    purchase_urgency: int = Field(default=5, ge=1, le=10, description="1 = no rush, 10 = needs it immediately")
    network_influence: int = Field(default=1, ge=1, le=10, description="How many peers they typically influence")
    
    bio: str = Field(..., description="2-3 sentence narrative describing this persona")


# ---------------------------------------------------------------------------
# Interaction & Social Events
# ---------------------------------------------------------------------------


class AgentInteractionEvent(BaseModel):
    """Single action taken by a simulated agent during the launch simulation."""

    agent_id: str
    interaction_type: InteractionType
    timestamp_offset_hours: float = Field(
        ..., ge=0, description="Hours after launch the event occurred"
    )
    reasoning: str = Field(..., description="Why the agent took this action")
    product_name: str


class SocialPost(BaseModel):
    """A simulated tweet, review, or Reddit comment."""

    agent_id: str
    platform: str = Field(..., description="twitter | reddit | product_hunt | app_store")
    content: str = Field(..., max_length=2000)
    sentiment: float = Field(..., ge=-1.0, le=1.0, description="-1 very negative, +1 very positive")
    timestamp_offset_hours: float
    upvotes: int = Field(default=0, ge=0)
    replies: list[str] = Field(default_factory=list, description="Simulated reply excerpts")


# ---------------------------------------------------------------------------
# Simulation Results / Metrics
# ---------------------------------------------------------------------------


class AdoptionDataPoint(BaseModel):
    hour: float
    cumulative_views: int
    cumulative_clicks: int
    cumulative_purchases: int
    conversion_rate: float


class ObjectionSummary(BaseModel):
    objection: str = Field(..., description="Core objection in plain language")
    frequency: int = Field(..., description="How many agents raised it")
    example_agents: list[str] = Field(..., description="Up to 3 agent_ids who raised it")


class SimulationMetrics(BaseModel):
    total_agents: int
    agents_who_viewed: int
    agents_who_clicked: int
    agents_who_purchased: int
    overall_conversion_rate: float
    average_sentiment: float
    top_objections: list[ObjectionSummary]
    adoption_curve: list[AdoptionDataPoint]
    key_insights: list[str] = Field(..., description="3-5 bullet insights from the Chronicler")


# ---------------------------------------------------------------------------
# API Request / Response envelopes
# ---------------------------------------------------------------------------


class SimulationRequest(BaseModel):
    product: ProductInput


class SimulationResponse(BaseModel):
    simulation_id: str
    status: SimulationStatus
    message: str = "Simulation queued"


class SimulationResult(BaseModel):
    simulation_id: str
    status: SimulationStatus
    product: ProductInput
    personas: list[SimulatedAgentProfile] = Field(default_factory=list)
    interactions: list[AgentInteractionEvent] = Field(default_factory=list)
    social_posts: list[SocialPost] = Field(default_factory=list)
    metrics: SimulationMetrics | None = None
    error: str | None = None


class InterviewRequest(BaseModel):
    question: str = Field(..., min_length=5, max_length=1000)


class InterviewResponse(BaseModel):
    agent_id: str
    agent_name: str
    answer: str
    purchased: bool
    reasoning_summary: str
